<div><x-input-label for="judul" value="Nama tujuan tabungan" /><x-text-input id="judul" name="judul" class="mt-1 block w-full rounded-xl border-slate-200 bg-slate-50 focus:border-emerald-500 focus:ring-emerald-500" value="{{ old('judul', $tabungan->judul ?? '') }}" required /><x-input-error :messages="$errors->get('judul')" class="mt-2" /></div>
<div><x-input-label for="target_nominal_display" value="Target nominal (Rp)" /><input id="target_nominal_display" type="text" inputmode="numeric" class="mt-1 block w-full rounded-xl border-slate-200 bg-slate-50 focus:border-[#7ED957] focus:ring-[#7ED957]" value="{{ old('target_nominal', $tabungan->target_nominal ?? '') ? number_format((float) old('target_nominal', $tabungan->target_nominal ?? ''), 0, ',', '.') : '' }}" required><input id="target_nominal" name="target_nominal" type="hidden" value="{{ old('target_nominal', $tabungan->target_nominal ?? '') }}"><x-input-error :messages="$errors->get('target_nominal')" class="mt-2" /></div>
<div><x-input-label for="target_tanggal" value="Target tanggal" /><x-text-input id="target_tanggal" name="target_tanggal" type="date" min="{{ now()->toDateString() }}" class="mt-1 block w-full rounded-xl border-slate-200 bg-slate-50 focus:border-emerald-500 focus:ring-emerald-500" value="{{ old('target_tanggal', isset($tabungan) ? $tabungan->target_tanggal->format('Y-m-d') : '') }}" required /><x-input-error :messages="$errors->get('target_tanggal')" class="mt-2" /></div>
<div><x-input-label for="foto" value="Foto (opsional, maksimal 2 MB)" /><input id="foto" name="foto" type="file" accept="image/*" class="mt-1 block w-full rounded-xl border border-slate-200 bg-slate-50 p-2 text-sm" /><x-input-error :messages="$errors->get('foto')" class="mt-2" /></div>
<script>
document.querySelectorAll('#target_nominal_display').forEach((display) => display.addEventListener('input', (event) => {
    const raw = event.target.value.replace(/\D/g, ''); event.target.value = raw.replace(/\B(?=(\d{3})+(?!\d))/g, '.'); document.getElementById('target_nominal').value = raw;
}));
</script>
